name: Code Quality

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - run: composer install --no-progress
      - run: vendor/bin/phpstan analyse --error-format=github

  codesniffer:
    name: CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - run: composer install --no-progress
      - run: vendor/bin/phpcs --report=checkstyle

  phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - run: composer install --no-progress
      - run: ./bin/phpunit tests/Unit/Controller/CategoryControllerTest.php
      - run: ./bin/phpunit tests/Unit/Service/Builder/CategoryUrlBuilderTest.php
      - run: ./bin/phpunit tests/Unit/Service/Importer/CategoryImporterTest.php